### ISSUE TITLE
Puzzle about singularity_run.sh

### ISSUE THREAD

**Issue by Yiyuiii** [Daffan/nav-competition-icra2022#2]
While I was following the instruction for building a Singularity container, one bug occured during executing the testing cmd:
> ./singularity_run.sh /path/to/image/file python3 run.py --world_idx 0

Outputs are,
```
WARNING: While finding nv bind points: could not retrieve ld cache: exec: "/usr/sbin/ldconfig.real": stat /usr/sbin/ldconfig.real: no such file or directory
WARNING: Could not find any nv files on this host!
WARNING: Could not find any nv libraries on this host!
>>>>>>>>>>>>>>>>>> Loading Gazebo Simulation with BARN/world_0.world <<<<<<<<<<<<<<<<<<
... logging to /home/cyy/.ros/log/682b7ed4-bb1f-11ec-929c-f1506ab41986/roslaunch-amax-104.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/parent.py", line 157, in _load_config
    roslaunch_strs=self.roslaunch_strs, verbose=self.verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 634, in _include_tag
    default_machine, is_core, verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 679, in _recurse_load
    self._param_tag(tag, context, ros_config, verbose=verbose)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/xmlloader.py", line 271, in _param_tag
    value = self.param_value(verbose, name, ptype, *vals)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslaunch/loader.py", line 536, in param_value
    p = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
^CTraceback (most recent call last):
  File "run.py", line 58, in <module>
    time.sleep(5)  # sleep to wait until the gazebo being created
```
My OS is Ubuntu 20.04 LTS, and I wish to run the env via Singularity. I'm not familar with Singularity and the fault couldnt get located yet. Could u give a hand?

**Comment by Daffan** [comment]
Hi what is the Singularity version are you using? Here is a pre-built Singularity image: https://drive.google.com/file/d/1s0MaQx-LwB7w6s274IY6R1nJgi8BAA8A/view?usp=sharing

Could you download and try whether this image works with this command: `./singularity_run.sh /path/to/image/file python3 run.py --world_idx 0`?

**Comment by Yiyuiii** [comment]
Thanks for your reply, my Singularity version is latest: [singularity-ce_3.9.8-focal_amd64.deb](https://github.com/sylabs/singularity/releases/download/v3.9.8/singularity-ce_3.9.8-focal_amd64.deb)
I've tried your Singularity image, codes run differently indeed.
last lines of the outputs are
```
process[move_base-1]: started with pid [566]
[ WARN] [1649868564.398887879, 2.259000000]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1649868564.400218631, 2.261000000]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1649868564.400984257, 2.261000000]: global_costmap: Using plugin "obstacles_layer"
[ INFO] [1649868564.425013371, 2.285000000]:     Subscribed to Topics: scan
[ INFO] [1649868564.443878271, 2.303000000]: global_costmap: Using plugin "inflater_layer"
[ WARN] [1649868564.492116542, 2.350000000]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1649868564.492521376, 2.350000000]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1649868564.493273043, 2.351000000]: local_costmap: Using plugin "obstacles_layer"
[ INFO] [1649868564.498807675, 2.356000000]:     Subscribed to Topics: scan
[ INFO] [1649868564.514725904, 2.371000000]: local_costmap: Using plugin "inflater_layer"
[ INFO] [1649868564.561254840, 2.416000000]: Created local_planner base_local_planner/TrajectoryPlannerROS
[ INFO] [1649868564.571054519, 2.425000000]: Sim period is set to 0.05
[ WARN] [1649868564.576008151, 2.430000000]: Parameter pdist_scale is deprecated. Please use the name path_distance_bias instead.
[ WARN] [1649868564.577367944, 2.431000000]: Parameter gdist_scale is deprecated. Please use the name goal_distance_bias instead.
[ INFO] [1649868564.736416275, 2.559000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1649868564.744082619, 2.565000000]: Recovery behavior will clear layer 'obstacles'
[ INFO] [1649868564.774971950, 2.586000000]: odom received!
>>>>>>>>>>>>>>>>>> Test finished! <<<<<<<<<<<<<<<<<<
Navigation succeeded with time 47.2030 (s)
Navigation metric: 0.1423
Traceback (most recent call last):
  File "run.py", line 177, in <module>
    with open(args.out, "a") as f:
OSError: [Errno 30] Read-only file system: 'out.txt'
```
It seems to work with your image, except a few errors:
```
[ERROR] [1649868561.366415697, 0.044000000]: GetModelState: model [jackal] does not exist
[ERROR] [1649868561.371062119, 0.048000000]: Updating ModelState: model [jackal] does not exist
[ERROR] [1649868561.375284833, 0.052000000]: GetModelState: model [jackal] does not exist
[ERROR] [1649868562.101178316, 0.188000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_left_wheel
[ERROR] [1649868562.102238443, 0.188000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_right_wheel
[ERROR] [1649868562.103248319, 0.188000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_left_wheel
[ERROR] [1649868562.104255362, 0.188000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/rear_right_wheel
```
I'm not sure whether this is natual.

**Comment by Daffan** [comment]
Thanks! Those errors don't hurt except for the OSError. I just pushed a small change to mount the current folder to the container, so that the program can write the test result to the `out.txt` file. I will check whether the latest version Singularity simply just cannot build the image, and I will bring it back to you ASAP.

**Comment by Yiyuiii** [comment]
Thanks for your patience, I'm looking forward to your result.

**Comment by Yiyuiii** [comment]
Well, I've solved this problem. The OSError was caused by the lack of execute permission, and the solution is running chmod 777 for ROS files from Github.
